[package]
name = "substrate-pallet-multi-account"
description = "A pallet/runtime module for Substrate with multisig functionality with a static `AccountId` and a dynamic `threshold` and set of `signatories`."
version = "2.0.0-alpha.8"
authors = ["Philip Stanislaus <6912756+philipstanislaus@users.noreply.github.com>"]
edition = "2018"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/substrate-pallet-multi-account/"

[dependencies]
serde = { version = "1.0.102", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
frame-support = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
frame-system = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
sp-core = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
sp-runtime = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
sp-std = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
sp-io = { version = "2.0.0-alpha.8", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }

[dev-dependencies]
sp-core = { version = "2.0.0-alpha.8", git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }
pallet-balances = { version = "2.0.0-alpha.8", git = "https://github.com/paritytech/substrate.git", rev = "7e9a2ae78d27cc56e053fbec3b34a1a258b89561" }

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
