[package]
name = "substrate-pallet-multi-account"
description = "A pallet/runtime module for Substrate with multisig functionality with a static `AccountId` and a dynamic `threshold` and set of `signatories`."
version = "2.0.0-rc6"
authors = ["Philip Stanislaus <6912756+philipstanislaus@users.noreply.github.com>"]
edition = "2018"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/substrate-pallet-multi-account/"

[dependencies]
serde = { version = "1.0.102", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-support = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
frame-system = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
sp-core = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
sp-runtime = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
sp-std = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
sp-io = { version = "2.0.0-rc6", default-features = false, git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }

[dev-dependencies]
sp-core = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }
pallet-balances = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "e41e935c3b38e8b2a30bb86c0c554f2071e0436c" }

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
