[package]
name = "pallet-multi-account"
version = "2.0.0-alpha.1"
authors = ["Philip Stanislaus <6912756+philipstanislaus@users.noreply.github.com>"]
edition = "2018"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/substrate-multi-account-pallet/"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
frame-support = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
frame-system = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
sp-core = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
sp-runtime = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
sp-std = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
sp-io = { version = "2.0.0-alpha.1", default-features = false, git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }

[dev-dependencies]
sp-core = { version = "2.0.0-alpha.1", git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }
pallet-balances = { version = "2.0.0-alpha.1", git = "https://github.com/paritytech/substrate.git", rev = "7c751574d8c53108e78440bfa5dffb80ab644972" }

[features]
default = ["std"]
std = [
	"serde/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
